### ISSUE TITLE
basic_publish of mandatory message on confirm channel returns None, but message is delivered

### ISSUE THREAD

**Issue by jbg** [amqp-rs/lapin#169]
```rust
// defined above: client, exchange_name, routing_key, data

let channel = await!(
    client.create_confirm_channel(Default::default())
        .compat()
)?;

let mut publish_options = BasicPublishOptions::default();
publish_options.mandatory = true;

let props = BasicProperties::default()
    .with_content_type("application/octet-stream".into())
    .with_content_encoding("bincode".into())
    .with_delivery_mode(2);

let res = await!(
    channel.basic_publish(exchange_name, routing_key, data, publish_options, props)
        .compat()
)?;

match res {
    Some(request_id) => info!("Message acked by RabbitMQ with request ID {}", request_id),
    None => error!("Message nacked by RabbitMQ"),
}
```

`basic_publish()` returns `None` and `Message nacked by RabbitMQ` is logged, but RabbitMQ successfully delivers the message to the queue bound to the specified exchange with the specified routing key.

I'm working to collect some more diagnostic information and will post it here once I do.

**Comment by Keruspe** [comment]
Heh, good timing, basic_publish is kind of special and is one of the two
things next on my TODO list of things that should be better handled (the
other one being « nowait »)

You should be able to try 0.19.0 alpha 3 next week with basic_publish
reworked

**Comment by jbg** [comment]
Thanks for giving `basic_publish` some attention!

I also noticed that the `basic.return` sent by RabbitMQ if there's no queue to route the message to doesn't seem to be handled:

```
ERROR lapin_async::channel > the client should not receive this method: Basic(Return(Return { reply_code: 312, reply_text: "NO_ROUTE", exchange: "ws", routing_key: "1557" }))
```

**Comment by Keruspe** [comment]
Nice catch, will sure help, thanks!

**Comment by Keruspe** [comment]
Basic return support is now tracked in #170
