### ISSUE TITLE
Optional options

### ISSUE THREAD

**Issue by fpagliughi** [amqp-rs/lapin#334]
Hi. Thanks for this project. 

I wonder if you would be open to a Pull Request that changes most of the parameter types for options to `Into<Option<SomeOptions>>`. That way any varible that the app wants to specify as a `default()` options parameter can be specified as `None` instead of having to spell out `SomeOptions::default()` every time. 

I think it would make the apps that use default options a little more compact and readable.

For example, if we make `Connection::connect()` look like this:

```
pub async fn connect<C>(uri: &str, options: C) -> Result<Connection>
where
    C: Into<Option<ConnectionProperties>>,
{
    let options = options.into().unwrap_or_default();
    Connect::connect(uri, options, OwnedTLSConfig::default()).await
}
```

We could call it like:

```
let conn = Connection::connect(&addr, None)
    .await
    .expect("connection error");
```

I'm already working this in a fork and would be happy to send it back here when I'm done.

**Comment by Keruspe** [comment]
Why the Into part? It could just be Option<SomeOptions> without the Into.

I fail to see how None is better than Default::default() (which can be used instead of SomeOptions::default())

**Comment by fpagliughi** [comment]
The Into part makes it backward compatible with what you already have. It doesn't break the existing applications in that you can still send a variable `opts` instead of being forced to change parameters to `Some(opts)`.

So in that case None _is_ equivalent to Default::default(). It's 75% fewer characters. Which his maybe silly, but looking at some of the code after None is put in, it does seem more readable overall.

Obviously another option would be to expand the API with different functions, like:
```
pub async fn connect(uri: &str) -> Result<Connection> { ... }
pub async fn connect_with_options(uri: &str, options: ConnectionProperties) -> Result<Connection> { ... }
```
...but a lot of the public functions in this library take a number of sets of options, so that doesn't seem like a great idea.

**Comment by fpagliughi** [comment]
Oh, but to be clear, if the parameter takes `Into<option<SomeOptions>>` then the application can use _any_ of these methods that we discussed. So it's left up to the user to decide which they prefer. The library is most flexible and doesn't dictate one way or another. 

All of this would compile...
```
let conn = Connection::connect(&addr, None).await?;

let conn = Connection::connect(&addr, Default::default()).await?;

let conn = Connection::connect(&addr, ConnectionProperties::default()).await?;

let props = ConnectionProperties::default().with_connection_name("pubsub-example".into());
let conn = Connection::connect(&addr, props).await?;
```

**Comment by Keruspe** [comment]
Does `Default::default()` here end up being None, or Some(Default::default()) ?

**Comment by fpagliughi** [comment]
If you pass in a value, you get the value. So if you explicitly pass in `Default::default()` then you get the defaults. But if you pass in `None` you also get the defaults. So the `None` value means "nothing more than the defaults". 

Again, this is mainly to make the application code a little more readable, especially in a library like this where a lot of functions take multiple sets of options, and apps often just uses the defaults.

From my MQTT library, you might implement it like:
```
pub fn disconnect<T>(&self, opts: T) -> Token
where
    T: Into<Option<DisconnectOptions>>,
{
    let opts = opts.into().unwrap_or_default();
```
So if it's `Some(val)`, you just unwrap it, and if it's `None` you use the defaults.

**Comment by Keruspe** [comment]
To sum things up:

- The only change in code that uses lapin is that you can use `None` instead of `Default::default()` and everything else works like before
- I understand `None` can be more convenient to use than `Default::default()`, but it's slightly less explicit, right? In the end, there will not be "no options" used, the default options will be used
- It makes the documentation harder to read, it just adds extra stuff that should just be hidden imo

Overall I don't think the tiny benefit is worth the added complexity added to the documentation
