### ISSUE TITLE
Basic.Deliver failure when using Kubernetes networking for v1.8.0

### ISSUE THREAD

**Issue by tadman** [amqp-rs/lapin#347]
For a non-obvious reason there seems to be an issue with Lapin operating within a Kubernetes container.

After a short period of time the consumer fails to properly forward incoming deliveries to the user code, despite continuing to send heartbeat notifications. 

I'm trying to identify the exact cause of the problem and narrow it down more precisely, but so far:

- Lapin client/server work fine on bare metal (Host OS) or within Docker, and/or a mixture of both
- Lapin server will stall after ~10s of being connected if run within Kubernetes regardless of how the RabbitMQ instance is hosted (Kubernetes, Docker, or external)

This problem does not occur with other RabbitMQ implementations (Node and Ruby both in use).

This could be an issue with Lapin, or any of the underpinning libraries, it's still unclear, but I'm digging deeper to find out more. This could be a quirk of how `async_io` and/or `epoll` works within the Kubernetes environment.

I've been capturing traces with Wireshark to try and understand the problem, but a rough timeline looks like:

- Protocol-Header 0-9-1
- Connection.Start
- Connection.Start-Ok
- Connection.Tune
- Connection.Open-Ok
- Connection.Open
- Connection.Open-Ok
- Queue.Declare q=hello
- Queue.Declare-Ok q=hello
- Basic.Consume q=hello
- Basic.Consume-Ok
- Heartbeat

Once established, the expected pattern is:

- Basic.Deliver x= rk=hello Content-Header Content-Body
- Basic.Ack
- Heartbeat

Instead what happens is:

- Basic.Deliver x= rk=hello Content-Header Content-Body
- Heartbeat
- Heartbeat

Without any `Basic.Ack` ever, it's just stuck.

Manually disconnecting the client from RabbitMQ will produce a disconnection in the error prior to the incidence of this issue, but not after. After it's as if the connection is frozen in some state.

I've built a minimal [demonstrator container](https://github.com/postageapp/lapin-kubes) based on the example in the Lapin README if anyone's interested in trying to reproduce the issue.

**Comment by tadman** [comment]
Looks like this is rectified in Lapin v2.0.0-alpha.4, which is great, but I've never seen an issue like this so strangely specific to runtime.

**Comment by Keruspe** [comment]
Does it still happen with 1.9.0?
