### ISSUE TITLE
Unexpected delay of 40 ms

### ISSUE THREAD

**Issue by RustPanda** [amqp-rs/lapin#354]
Hi, I'm using lapin from tokyo. I start 3 test services: sender -> proxy -> echo. Typically, when receiving a message from a request to the sender, there is a delay of 40 ms.
I'm using Jaeger tracing, you can see what is being called:
```rust
channel.basic_publish(
                EXCHANGE_NAME,
                route,
                BasicPublishOptions::default(),
                payload.as_slice(),
                properties,
            )
```
but the `consumer.next ().await `call only happens after 40+ ms:
```rust 
while let Some(Ok(delivery)) = consumer.next().await {
***
}
```
There is a 30% chance of delay

**Comment by Keruspe** [comment]
Hi,

Any chance you can use tcpdump / wireshark to see if the delay is caused by:
- waiting for packets to be sent on the network
- waiting for packets to be received on the network
- in the actual code
