### ISSUE TITLE
Can not run examples

### ISSUE THREAD

**Issue by vsilent** [amqp-rs/lapin#355]
How do I run any example code ? 
Shouldn't  there be a  Cargo.toml file included into examples directory ?

**Comment by Keruspe** [comment]
`cargo run --example=connection` will run examples/connection.rs

**Comment by vsilent** [comment]
I would add following to README.md

## Run an example code using following commands:

```

➜  docker run -p 15672:15672 -p 5672:5672 -e RABBITMQ_DEFAULT_USER=rmq -e RABBITMQ_DEFAULT_PASS=rmq  rabbitmq:3.8.4-management
➜  export AMQP_ADDR='amqp://rmq:rmq@localhost:5672/%2f'
➜  cargo run --example=connection

```
