### ISSUE TITLE
Error using exchange_declare(). Can't create exchange

### ISSUE THREAD

**Issue by fabracht** [amqp-rs/lapin#356]
Hello,
I'm using lapin version 1.9, and when I try to create a new exchange with exchange_declare(), I get the following error.
`Channel closed on channel 1 by 40:10 => AMQPError { kind: Soft(NOTFOUND), message: ShortString("NOT_FOUND - no exchange 'test_exchange' in vhost 'dnsgymgs'") } => NOT_FOUND - no exchange 'test_exchange' in vhost
`

These are the arguments:
`
let declare_options = ExchangeDeclareOptions {
           passive: true,
           durable: false,
           auto_delete: true,
           internal: false,
           nowait: true,
       };
self.channel
            .exchange_declare(
                "test_exchange",
                ExchangeKind::Topic,
                declare_options,
                FieldTable::default(),
            ).await           
`
I'm not sure what's going on here. Am I using the wrong method?
Thank you

**Comment by Keruspe** [comment]
Hi,

That's what passive is for, it doesn't create anything, just success if it exists or error otherwise
