### ISSUE TITLE
Generic INTERNALERROR where using ShortString in headers

### ISSUE THREAD

**Issue by nappa85** [amqp-rs/lapin#360]
When publishing to rabbit, if I use a ShortString as header, I get this error log:
```
ERROR lapin::channel: Connection closed on channel 0 by 0:0 => AMQPError { kind: Hard(INTERNALERROR), message: ShortString("INTERNAL_ERROR") } => INTERNAL_ERROR    
ERROR lapin::channels: Connection error: protocol error: AMQP hard error: INTERNAL-ERROR: INTERNAL_ERROR
```

I can imagine this is a RabbitMQ problem and not a real Lapin problem, is it possible to hard deprecate ShortString (since it's commented as deprecated) if they're unused, or maybe add a check on headers to avoid ShortString usage there?
Last resort is to improve error reporting, but I can image that if rabbit replies an error without context you can't do nothing about it.

**Comment by Keruspe** [comment]
ShortString is required for some parts of AMQP (despite being deprecated), so we need to keep it.
That being said, unless you have a good reason to use it, always prefer LongString.
In headers, ShortString is indeed not supported by rabbitmq-server
