### ISSUE TITLE
Consumer delegate static lifetime

### ISSUE THREAD

**Issue by r2dliu** [amqp-rs/lapin#361]
Relatively new to rust so possible I'm just being dumb.  

What would be a good workaround for accessing something in the closure of a consumer delegate without violating the static lifetime requirement?

In my use case, I have a connection pool for a database that I want to be able to access. 

simplified pseudocode:
```
main() {
  let pool = create_db_pool();
  consumer.set_delegate(|delivery: DeliveryResult| async {
         do_db_things(&pool, delivery) // compiler is unhappy because of static lifetime
  }
}
```

errors:

```
`pool` is borrowed here
closure may outlive the current function, but it borrows `pool`, which is owned by the current function
may outlive borrowed value `pool`
```

closure obviously does not outlive the pool since the program will end there but not sure how to explicitly tell rust that it's fine to be using it

**Comment by tdejager** [comment]
You could try moving the async closure. However, this is more of a common rust/async question than specific to lapin.

**Comment by cdbennett** [comment]
If the DB pool was only used in the delegate, you could simply `move` it into the closure (change to `async move`).

But in a real application the DB pool would probably be used by other tasks / modules as well, e.g. web server, etc., and in that case you need to share the DB pool. Do this with the usual Rust method for sharing state -- use an `Arc<T>` if immutable, or `Arc<Mutex<T>>` if you need mutable access.

```rs
fn main() {
    let pool = Arc::new(create_db_pool());
    consumer.set_delegate(|delivery: DeliveryResult| {
        let pool = Arc::clone(&pool); // Arc value for this task
        async move {
         do_db_things(&pool, delivery)
        }
    });
}
```

Here's a little demo of how you might use `Arc<T>` to share state across tasks: [Rust Playground Snippet Link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ab632561467f03ef0ca29f76739eb00a)

**Comment by Keruspe** [comment]
As stated, this is not really a lapin problem but rather a generic rust async one.
