### ISSUE TITLE
Heartbeat timeout handling

### ISSUE THREAD

**Issue by ystasivs** [amqp-rs/lapin#364]
Hello,  i wonder how client handles heartbeat timeout.
From source it's clear to me that new valid heartbeat from server does nothing but just log. Is it possible to run within lapin custom handler that will do the reconnect on timeout?

**Comment by Keruspe** [comment]
A heartbeat timeout will trigger a connection error, resolving all pending futures with an error.

Lapin currently doesn't support automatic reconnection as of now (see #312 )

**Comment by Keruspe** [comment]
You can also register a callback here which will be called: https://docs.rs/lapin/latest/lapin/struct.Connection.html#method.on_error
