### ISSUE TITLE
Connecting to non-existing vhost can hang the program

### ISSUE THREAD

**Issue by prk3** [amqp-rs/lapin#367]
The following program can get stuck at the `.await` when vhost `bad` does not exist.

```rust
#[tokio::main(flavor = "current_thread")]
async fn main() {
    let conn = lapin::Connection::connect(
        "amqp://rabbitmq_user:rabbitmq_passwd@localhost:5672/bad",
        lapin::ConnectionProperties::default(),
    )
    .await;

    match conn {
        Ok(_conn) => {
            println!("connected");
        }
        Err(_error) => {
            println!("error");
        }
    }
}
```

```toml
[dependencies]
lapin = "2.1.0"
tokio = { version = "1.17", features = ["full"] }
```

It is not consistent though. In ~50% of the cases the future never resolves, in the other ~50% it returns `Err(_)`. The workaround I used is specifying timeout with `deadpool_lapin` crate.

Affected lapin versions: 2.0.0, 2.1.0, **lapin 1.9.0 and 1.10.0 work ok, that is they always return Err(_)**
Runtime: tokio 1.17
RabbitMQ version: 3.9
OS: Linux 5.16.12

**Comment by Keruspe** [comment]
Thanks, shouldn't e too hard to track down

**Comment by Keruspe** [comment]
I can indeed reproduce locally
