### ISSUE TITLE
How to correlate published messages with wait_for_confirms?

### ISSUE THREAD

**Issue by Roger** [amqp-rs/lapin#369]
I'm trying to use `confirm_select` and `wait_for_confirms` to get the list of acked/nacked messages, but every time I call `wait_for_confirms` it returns an empty `Vec`, even in the [example is checking `is_empty` after publishing some messages](https://github.com/amqp-rs/lapin/blob/main/examples/publisher_confirms.rs#L108).

With logs at trace level, I can see `PublisherConfirm was ready but didn't carry a message, discarding` that comes from https://github.com/amqp-rs/lapin/blob/main/src/returned_messages.rs#L149 so looks like the `Ack` doesn't carry any message.

Is there any way to know which published message was acked/nacked?

**Comment by Roger** [comment]
is `wait_for_confirms` more efficient than wait for each result of `basic_publish`? or internally is just waiting for each result?

**Comment by Keruspe** [comment]
The internal mechanism is the same, but wait_for_confirms will only wait
for the last publish
