### ISSUE TITLE
can not connect if password contains #$

### ISSUE THREAD

**Issue by constlhq** [amqp-rs/lapin#370]
My rabbit password contains `#$` and lapin can not connect to rabbit-server. Then I changed rabbit password it worked. not sure it caused by `#` or `$`

**Comment by Keruspe** [comment]
Are you connecting through an uri? (Most likely your answer here will be yes I think)

You need to url encode the password (as per the uri specifications) like you would do for things other than AMQP too. Then it should work

**Comment by Keruspe** [comment]
Try replacing # with %23 and $ with %24 in the AMQPUri when the actual password still contains # and $

**Comment by constlhq** [comment]
exactly, thanks!
