### ISSUE TITLE
TLS Authentication fails when using OpenSSL V3.0.2

### ISSUE THREAD

**Issue by noelatmerqury** [amqp-rs/lapin#379]
# Issue summary

Generating certificates using OpenSSL v3.0.2 will return the error

```rustc
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IOError(Custom { kind: InvalidData, error: ASN1Error { kind: Invalid } })', controller/src/main.rs:45:6
```

To solve this problem when generating `pkcs12` certificates, the `-legacy` option needs to be set. Once pkcs12 certificates are generated using the `-legacy` option, it all works fine.

## Generating pkcs12 certificate

```bash
openssl pkcs12                   \
    -legacy          \
    -export          \
    -inkey user.key  \
    -in user.pem     \
    -out user.p12    \
    -passout pass:""
```

# Resolution

Update the `pkcs12` certificate parsing to handle the OpenSSL v3 generated certificates.

# Rust details
rustc: `rustc 1.69.0 (84c898d65 2023-04-16)`
lapin: `lapin = { version="2.1.2", features = ["rustls", "rustls-native-certs"] }`

# System details
Operating System: `Ubuntu 22.04`
Openssl version: `OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)`

# Helpful information

OpenSSL have a migration guide [here](https://www.openssl.org/docs/man3.0/man7/migration_guide.html) that deals with the updates to the `PKCS#12 API updates`

**Comment by Keruspe** [comment]
Please fill this issue against https://github.com/hjiayz/p12 as it is the crate used to parse the pkcs12 and which emits this error
