### ISSUE TITLE
Restore Topology Example Fails

### ISSUE THREAD

**Issue by percybolmer** [amqp-rs/lapin#385]
Hey! 

Was interested in using the restore topology, and i tested the example.

It crashes however when trying it.

```bash
        "x-dead-letter-exchange": {
          "LongString": "test-exchange"
        },
 ```
 
 This part says that it is an invalid string, expects a Sequence.

**Comment by Keruspe** [comment]
You're right, this is due to the change where we now use a binary slice to back these. Will fix it
