### ISSUE TITLE
Possible to connect via a SOCKS5 proxy?

### ISSUE THREAD

**Issue by HerbCSO** [amqp-rs/lapin#386]
I'm pretty new to Rust, so this may be an obvious question, but is it possible to connect to RMQ via a SOCKS5 proxy using Lapin? I've setup a stream using `fast_socks5`, but I can't figure out a way to pass this into the Lapin `Connection` object. I tried using the custom_tls_connection example, but that doesn't seem to allow for a way to pass the stream I created into it?

Am I going about this entirely the wrong way?

```rust
    use fast_socks5::client::{Config, Socks5Datagram};

    // Create a tunnel through the SOCKS proxy
    let mut config = Config::default();
    config.set_skip_auth(true);
    let backing_socket = TcpStream::connect("127.0.0.1:1080").await.unwrap();
    let stream = Socks5Datagram::bind(backing_socket, rmq_host);

    // Now how do I pass this stream to Lapin...?
```

**Comment by Keruspe** [comment]
There might be a piece missing for this, I'll give it a look

**Comment by Keruspe** [comment]
So, it would be feasible quite simply, if you have a socks crate that is not async.

For now lapin only supports sync streams (lapin handles the async on top of that).

It is planned in the future to switch to async streams but I didn't get the time to do that just yet.

**Comment by HerbCSO** [comment]
Thank you for that. I'll be honest, I'm not sure how to accomplish that just yet (mostly due to being a Rust newbie ;] ), but in principle that makes sense to me. So I'll close this.
