### ISSUE TITLE
add Clone where it makes sense

### ISSUE THREAD

**Issue by alekspickle** [amqp-rs/lapin#391]
I am trying to create even higher level wrapper for amqp operations and it would make sense to save connection as a passable around object, but some parts of `lapin::Connection` do not implement `Clone`, however almost all of the underlying types are.

The ones that still do not are: `ConnectionCloser` and `Connection` itself. 
Then I could just do something like this:

```

pub struct Rabbit(Connection);

impl Rabbit {
    pub async fn new(uri: &str) -> Self {
        let con = Connection::connect_uri(uri.clone(), ConnectionProperties::default()).await?;
        Self(con)
}
}


```

If it sounds good here is the PR #390

**Comment by Keruspe** [comment]
Connection doesn't require &mut for anything, why not just using an Arc<Connection> ?

**Comment by Keruspe** [comment]
With your changes the connection would get closed when the first reference is dropped for example. It just brings unnecessary complexity imo

**Comment by alekspickle** [comment]
huh, I guess I missed that Drop impl, thanks for clarification!
