### ISSUE TITLE
A Tokio 1.x context was found, but it is being shutdown.

### ISSUE THREAD

**Issue by JasterV** [amqp-rs/lapin#393]
Hello there,

I implemented an application that uses lapin to purely publish messages. 
It is used as a cronjob that will spawn many tens of threads concurrently and for each one it creates a single channel that will publish a message.
The main logic looks something like this:

main.rs
``` rust
core::run(
        Arc::from(message_service),
        config.max_concurrent_tasks,
    )
    .await?;
```

core.rs
```rust
use futures_util::stream::{self, StreamExt};

pub async fn run(
    message_service: Arc<dyn MessageService>,
    max_concurrent_tasks: usize,
) -> anyhow::Result<()> {
    let messages = get_messages_to_send().await?;
    stream::iter(messages)
        .for_each_concurrent(max_concurrent_tasks, move |message| {
            let message_service = message_service.clone();
            send_message(message_service, &message.id)
        })
        .await;

    Ok(())
}

async fn send_message(
    message_service: &dyn MessageService,
    message_id: &str,
) -> Result<(), SendMessageError> {
    message_service
        .publish_event(MyMessage {
            // content        
        })
        .await?;
    Ok(())
}
```

message_service.rs
```rust
#[async_trait]
pub trait MessageService: Send + Sync {
    async fn publish_event<T: Serialize + Debug + Send + Sync>(&self, event: T) -> Result<(), PublishEventError<T>>;
}
```

lapin_adapter.rs
```rust
#[async_trait]
impl MessageService for AmqpAdapter {
    async fn publish_event<T: Serialize + Debug + Send + Sync>(
        &self,
        event: T,
    ) -> Result<(), PublishEventError> {
        let channel = self
            .client
            .create_channel()
            .await?;

        // Publish message and everything
 
        // Here the channel should just drop and everyone should be happy
        Ok(())
    }
}
```

But for some reason, when the execution of the `core::run` function ends and the application is about to shut down, we get the following errors:

![image](https://github.com/amqp-rs/lapin/assets/49537445/34003555-6dab-4326-b06d-68841a87548e)

![image](https://github.com/amqp-rs/lapin/assets/49537445/b637b51a-5a6a-4d7d-9295-5caa5cc82bdc)

![image](https://github.com/amqp-rs/lapin/assets/49537445/09066c9a-56c7-4620-8844-5fc4eb1d18a6)

Note that this error happens most of the time but not always, and I haven't been able to reproduce it locally consistently

**Comment by janlegner** [comment]
We are getting same issue in our environment as well. Did you have any luck solving this @JasterV?

**Comment by JasterV** [comment]
@janlegner honestly after trying everything I knew of (Including making totally sure that all channels and connections were closed before shutting down) I couldn't get rid of this error, and so I moved to [`amqprs`](https://github.com/gftea/amqprs).
The transition was very smooth and it works with no errors :)

**Comment by janlegner** [comment]
@JasterV thanks a lot for the suggestion!

**Comment by Keruspe** [comment]
Are you actually using tokio?

Could you provide a minimal reproducer or a hit repo where you have the problem ?

**Comment by Keruspe** [comment]
This is mostly due to the lack of async drop in rust. We spawn futures on the executor in the Drop method because of this iirc.

You might want to explicitent càll connection.close before exiting your "main" future
