### ISSUE TITLE
Acker struct provides no way to reference elsewhere and/or check if (n)acking has already been done

### ISSUE THREAD

**Issue by Victor-N-Suadicani** [amqp-rs/lapin#402]
If I have a delivery, I can take the acker out like so:

```rust
let delivery: Delivery = ...;
let acker = std::mem::take(&mut delivery.acker);
```

I find this kind of weird. Now the delivery has a default acker that probably makes no sense. And now I can ack the delivery and the acker separately?

It would be nice if I could somehow clone the acker to refer to the same underlying acker. Maybe something like this:
```rust
let delivery: Delivery = ...;
let acker = delivery.acker.clone();
```
If the acker was in some form of `Arc` perhaps. This way, `acker` and the `delivery`'s acker would refer to the same underlying acker.

Would something like this be possible?

**Comment by Keruspe** [comment]
Wait, why would you take the acker out of the delivery?

The Acker is not cloneable by design (actually, it was initially, and we removed that because you really shouldn't do that).

Please explain the big picture of what you're trying to do

**Comment by Victor-N-Suadicani** [comment]
This comes from a use case in https://github.com/issuu/kanin.

So the big picture is that in most cases, I want to simply take the data of the delivery and deserialize it into some type, do some processing on it in a "handler" and then ack the message. But in some cases, the handler may want to customize its acking behaviour, like rejecting when an error occurs or whatever.

These handlers may run on other threads than where the delivery originated.

Pseudo-code:
```rust
let delivery: Delivery = ...;
let acker = std::mem::take(&mut delivery.acker);
let deserialized: T = delivery.data.decode();

// Case 1: Most handlers don't need the acker.
handler(deserialized);

// Case 2: But some handlers want to customize the ack/reject behaviour.
handler(deserialized, acker);

// Do I now ack here or not?
acker.ack(...)
```

The only way to know whether I took the acker out is to do `delivery.acker == Acker::default()`. This feels very hacky.

From a pure API design standpoint, I really don't understand why `Acker` implements `Default` to begin with - how does it make sense that I can produce an Acker out of thin air like in `Acker::default()`? And it allows this weird usage through `std::mem::take`, leaving the delivery in a strange state.

Essentially I would like some kind of API that would allow me to share the acker out to other threads and then also check if the acker has already been used to ack/reject a message.

**Comment by Keruspe** [comment]
You're 100% right.
Acker never should have implemented Default. I'm not sure why it was in the first place... sounds like it just made writing tests easier which is a pity. Default Acker doesn't do anything when called...

Anyways, enough with the past. It doesn't implement Clone because we didn't have proper mechanism to prevent it from being called twice back then iirc, but we implemented that since then.

I've just added a Clone impl and a method to check whether it has already been used. Will publish soon.

Btw, Acker is only some kind of syntactic sugar/shortcut and you also can call e.g. basic_ack on the Channel too with the same effect (but without the check of it already having been used).

I'm tempted to remove the Default impl as it's definitely a glitch, but that would also be a breaking change so... 😕

**Comment by Victor-N-Suadicani** [comment]
>Btw, Acker is only some kind of syntactic sugar/shortcut and you also can call e.g. basic_ack on the Channel too with the same effect (but without the check of it already having been used).

That's a good point, I hadn't actually considered that, mostly because I'd need to access the delivery tag separately then. But I guess I could just do that somehow.

>I'm tempted to remove the Default impl as it's definitely a glitch, but that would also be a breaking change so... 😕

Yea 🤷. You can't even mark it as deprecated as it's a trait impl... The best you could do is log a warning when producing a default acker I guess.
