### ISSUE TITLE
A cleaner way to limit tokio spawn than a tokio::sync::Semaphore

### ISSUE THREAD

**Issue by doubleailes** [amqp-rs/lapin#410]
Hello,

I would like to limit the number of spawn thread when using tokio executor.

I end up using
```rust
 let semaphore = Arc::new(Semaphore::new(32));
    consumer.set_delegate(move |delivery: DeliveryResult| {
        let semaphore_clone = Arc::clone(&semaphore);
        async move {
            let _permit = semaphore_clone.acquire().await;
        ....}
```

Is there a cleaner to deal with it?

**Comment by Keruspe** [comment]
The number of threads should be defined in the tokio configuration.
We don't spawn threads here, we only spawn "tasks", which are often called e.g. "green threads" in other languages you might be more familiar with. Depending on the load of spawn threads, tokio adds some more depending on your configuration, but it definitely runs tens of tasks per thread

**Comment by Keruspe** [comment]
If you want to limit the number of tasks, what you probably are looking good for is actually limiting the number of messages you prefetch. By default an AMQP consumer will fetch all available messages (while processing them). Using a semaphore like you do won't prevent lapin from fetching more messages in the background and queuing them locally which can be used a lot of memory if you have a lot of messages.

See channel.basic_qos method. By default it's a limit for the channel (there sadly isn't a limit only for one consumer), if you set the global to true, it will be a limit for the whole connection. This setting is handled server side, it's not specific to lapin

**Comment by Keruspe** [comment]
I'm happy to accept a PR explaining this in the documentation if you're happy with the solution and are willing to contribute, I can assist in finding the right place for it

**Comment by Keruspe** [comment]
Actually, the global option behaves differently in rabbitmq than in the spec, see associated documentation : https://www.rabbitmq.com/docs/consumer-prefetch
