### ISSUE TITLE
disable tls support, including avoid bring in those deps

### ISSUE THREAD

**Issue by mark-e-hoffman** [amqp-rs/lapin#411]
We don't use tls with our app using the lapin crate. We have a customer who's lawyers are very sticky about licenses and the crates brought to support tls (rustls-webpki, rustls) have licenses info that they are not completely comfortable with. Is there any way configure Cargo for lapin where these deps are not included?

Thanks

**Comment by Keruspe** [comment]
Hello,

If disabling default features is not enough, I'll fix that in a new major version which should come soon

**Comment by Keruspe** [comment]
Hello @mark-e-hoffman 
Closing since disabling default features does exactly what you want (note that you'll need to enable a default runtime starting with 3.0 if you do that)
