### ISSUE TITLE
Add with_type() message property function

### ISSUE THREAD

**Issue by dnlsndr** [amqp-rs/lapin#412]
According to the AMQP 0.9.1 docs (https://www.rabbitmq.com/docs/publishers#message-properties), there's a message property called "type". I'm currently integrating against a 3rd party provider that requires this property for routing. It seems though, that I can not set up this property in the BasicProperties struct.
Is it acceptable to implement this into the library? 
I can create a PR for that, if you wish.

**Comment by dnlsndr** [comment]
I just had another look at the source code, and noticed that there's a "kind" property. Is that equivalent to the "type" property?

**Comment by dnlsndr** [comment]
Ah yes, that is indeed the case :) closing

**Comment by Keruspe** [comment]
This should probably be better documented. That's because type is a reserved keyword iirc

**Comment by dnlsndr** [comment]
yeah, maybe it would still be possible to add a "with_type" alias function, as that does not collide wi

**Comment by Keruspe** [comment]
Fixed in amq-protocol 7.2.1

**Comment by Keruspe** [comment]
It's now automatically pulled by lapin 2.4
